/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package athena.terraform.java.jdbc.exception.repro;

import com.amazon.athena.jdbc.AthenaDriver;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

public class App {


    public static void main(String[] args) throws SQLException {
        Properties connectionParameters = new Properties();
        connectionParameters.setProperty("Workgroup", "athena-jdbc-repro-workgroup");
        connectionParameters.setProperty("Region", "us-east-1");
        connectionParameters.setProperty("Catalog", "AwsDataCatalog");
        connectionParameters.setProperty("Database", "athena-jdbc-repro");
        connectionParameters.setProperty("CredentialsProvider", "ProfileCredentials");
        connectionParameters.setProperty("ProfileName", "default");
        String url = "jdbc:athena://";
        AthenaDriver driver = new AthenaDriver();
        Connection connection = driver.connect(url, connectionParameters);

        // These queries work
        executeQuery(connection, "SELECT * from test");
        executeQuery(connection, "SELECT * from props");

        // This query works
        executeQuery(connection, "SHOW TBLPROPERTIES props");

        // This query fails
        executeQuery(connection, "SHOW TBLPROPERTIES test");
    }

    private static void executeQuery(Connection connection, String query) throws SQLException {
        Statement statement = connection.createStatement();
        ResultSet resultSet = statement.executeQuery(query);
        while (resultSet.next()) {
            System.out.println(resultSet.getString(1));
        }
    }
}
